config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :buckets  , only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :availables
    end
    resources :galleries, only: [:update]
    get "/" => "administration#index"
  end
  resource :home, controller: :home, only: [] do
    get "index" => "home#index"
    get "terms" => "home#terms"
  end
  devise_for :users
  root 'home#index'
  get  'index.html' => 'home#index'
  get  'feedback'   => 'home#feedback'
  resources :buckets, only: [:index,:show,:index_grid]
  resources :organizations
end

app/models/available.rb
class Available < ActiveRecord::Base
  belongs_to :bucket
end

app/models/bucket.rb
class Bucket < ActiveRecord::Base
  # Alias for acts_as_taggable_on :tags
  acts_as_taggable
  acts_as_taggable_on :tags

  has_many   :galleries
  has_many   :order_items
  has_many   :availables
  belongs_to :organization
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :bucket
  belongs_to :organization
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many   :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :bucket
  belongs_to :order
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :buckets
  has_many :galleries
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  before_create :set_default_organization
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :organizations
  has_many :orders
  private
  def set_default_organization
      self.organization ||= "台灣黑客松"
  end
end

app/controllers/admin/admin_base_controller.rb
class Admin::AdminBaseController < ApplicationController
  before_action :redirect_if_not_admin

  def redirect_if_not_admin
    if not admin_signed_in?
      redirect_to root_path
    end
  end

  def admin_signed_in?
    user_signed_in?
  end

end

app/controllers/admin/administration_controller.rb
class Admin::AdministrationController < Admin::AdminBaseController

  # GET /admin/manage_home
  def index
  end

 private

end

app/controllers/admin/buckets_controller.rb
class Admin::BucketsController < Admin::AdminBaseController

  before_action :set_admin_bucket, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
    @admin_bucket = Bucket.new
  end

  def create
    @admin_bucket = Bucket.new admin_bucket_params
    if @admin_bucket.save
      current_user.organizations.first.buckets << @admin_bucket
      Gallery.create bucket: @admin_bucket, name: "gallery",
        image: Rails.root.join('db/image/dummy_square.jpg').open
      redirect_to edit_admin_bucket_path @admin_bucket
    else
      redirect_to new_admin_bucket_path
    end
  end

  def edit
  end

  def update
    @admin_bucket.update admin_bucket_params
    respond_to :js
  end

  def destroy
    @admin_bucket.delete
  end

 private

  # Use callbacks to share common setup or constraints between actions.
  def set_admin_bucket
    @admin_bucket = Admin::BucketDecorator.new Bucket.find(params[:id])
  end

 # Never trust parameters from the scary internet, only allow the white list through.
  def admin_bucket_params
    params.require(:admin_bucket).permit(:title, :description, :quantity, :price, :aasm_state)
  end

end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < Admin::AdminBaseController
  before_action :set_admin_gallery, only: [:update]

  def update
    @admin_gallery.update(admin_gallery_params)
    respond_to :js
  end

  private

  def set_admin_gallery
    @admin_gallery = Gallery.find(params[:id])
  end

  def admin_gallery_params
    params.require(:admin_gallery).permit(:name, :image, :text)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_user
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation,:current_password,:organization) }
  end

  private
  def set_user
    if not user_signed_in?
      @user = User.new
    end
  end
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  before_action :set_bucket, only: [:show]

  def index
      @bucket = Bucket.all
  end

  def index_grid
      @bucket = Bucket.all
  end

  def show
  end

  private
  def set_bucket
      @bucket = Bucket.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def feedback
  end

  def terms
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show]
  def index
    @organizations = Organization.all
  end

  def show
  end

  private

  def set_organization
    @organization = Organization.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/administration/index.html.erb
<div class="row" style="margin-bottom: 180px">
  <div class="col-md-5 col-md-offset-2">
    <div class="project-container">
      <div class="project-header">
        <a class="project-thumb lightbox" href="<%= admin_buckets_path %>" 
           data-lightbox-group="dummy-projects"
           style="height: 70px">
          <span class="overlay" style="background-color: rgba(167, 151, 156, 0.9);"></span>
        </a>
        <ul class="custom-list project-tags">
          <li>編輯物品，</li>
          <li>瀏覽物品</li>
        </ul>
      </div>
      <div class="project-content">
        <h1 class="project-title"><a href="<%= admin_buckets_path %>">
          管理物品 </a></h1>
        <h5 class="project-category"> manage buckets </h5>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="project-container">
      <div class="project-header">
        <a class="project-thumb lightbox" href="<%= new_admin_bucket_path %>" 
           data-lightbox-group="dummy-projects"
           style="height: 70px">
          <span class="overlay" style="background-color: rgba(167, 151, 156, 0.9);"></span>
        </a>
        <ul class="custom-list project-tags">
          <li>新增物品</li>
        </ul>
      </div>
      <div class="project-content">
        <h1 class="project-title"><a href="<%= new_admin_bucket_path %>"> 新增物品 </a></h1>
        <h5 class="project-category"> new buckets </h5>
      </div>
    </div>
  </div>
</div>

app/views/admin/buckets/_bucket.html.erb
<!-- PROPERTY : begin -->
<li class="property first-in-row odd" id="bucket<%= bucket.id %>">
  <a href="#" class="property-thumb">
    <img src="<%= bucket.galleries.first.image.list.url %>" alt="">
    <span class="overlay"><span><i class="fa fa-search"></i> View More</span></span>
  </a>
  <div class="property-content">
    <h4 class="property-title"><a href="#"><%= bucket.title %></a></h4>
    <h5 class="property-location"><%= current_user.organization %></h5>
    <p class="property-description"><%= bucket.description %></p>
    <ul class="custom-list property-icons">
      <li class="beds" title="beds"><i></i>2</li>
      <li class="people" title="people"><i></i>4</li>
      <li class="bathrooms" title="bathrooms"><i></i>1</li>
    </ul>
    <div class="property-price-rating">
      <div class="property-price"><strong>$ <%= bucket.price%> </strong> / 天</div>
      <div class="property-rating"><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></div>
      <a class="button" href="<%= edit_admin_bucket_path bucket %>"> 
        <i class="fa fa-edit"></i> 編輯 </a>
      <%= link_to admin_bucket_path(bucket), class: "button color-2", method: :delete, remote: true do %>
        <i class="fa fa-minus"></i> 刪除 </a>
      <% end %>
  </div>
</li>
<!-- PROPERTY : end -->

app/views/admin/buckets/destroy.js.erb
var item = $('#bucket<%= @admin_bucket.id %>');
item.fadeOut(300, item.remove());

app/views/admin/buckets/index.html.erb
<!-- CORE : begin -->
<div id="core" class="page-search-results">
  <!-- PAGE HEADER : begin -->
  <div class="page-header">
    <div class="container">
      <div class="page-header-inner clearfix">
        <h1>Search Results - XXX Objects</h1>
        <ul class="custom-list breadcrumbs">
          <li><a href="<%= admin_path %>"> 我的物品 </a> / </li>
          <li><a href="<%= admin_buckets_path %>"> 管理物品 </a></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- PAGE HEADER : end -->

  <!-- MAIN WRAPPER : begin -->
  <div class="main-wrapper-container">
    <div class="container">
      <div id="main-wrapper" style="background:#fff;">
        <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <%= render "properties_listing" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- MAIN WRAPPER : end -->

</div>
<!-- CORE : end -->

app/views/admin/buckets/new.html.erb
<!-- CORE : begin -->
<div id="core">
  <!-- CONTENT SECTION - SERVICES : begin -->
  <section class="content-section row">
    <div class="container">
      <div class="col-md-3">
        <h2>新增物品</h2>
      </div>
      <div class="col-md-9">
        <%= form_for @admin_bucket, as: :admin_bucket, url: admin_buckets_path,
          html: {class: "form-horizontal"} do |f| %>
          <div class="form-group">
            <%= f.label :title, "標題", class: "col-sm-2 control-label"%>
            <div class="col-sm-10">
              <%= f.text_field :title, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :quantity, "數量", class: "col-sm-2 control-label"%>
            <div class="col-sm-10">
              <%= f.number_field :quantity, class: "form-control", 
                                 min: 1, value: 1%>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :price, "價格", class: "col-sm-2 control-label"%>
            <div class="col-sm-10">
              <%= f.text_field :price, class: "form-control", value: "10" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :description, "描述", class: "col-sm-2 control-label"%>
            <div class="col-sm-10">
              <%= f.text_area :description, class: "form-control" %>
            </div>
          </div>
          <br>
          <%= f.submit "新增物品", class: "button", style: "width: 100%" %>
        <% end %>
      </div>
    </div>
  </section>
</div>
<!-- CORE : end -->

app/views/admin/galleries/update.js.erb
$('#gallery-upload').find('img').attr('src', "<%= @admin_gallery.image.thumb.url %>");

app/views/buckets/show.html.erb
  <!-- CORE : begin -->
  <div id="core" class="page-property-details">

  <!-- PAGE HEADER : begin -->
  <div class="page-header" style="background-image:url(/images/show_cover.jpeg);">
    <div class="container">
      <div class="page-header-inner clearfix">
        <h1><%= @bucket.title %></h1>
        <ul class="custom-list breadcrumbs">
          <li><a href="/">Home</a> / </li>
          <li><a href="/buckets/">Search Results</a> /</li>
          <li><a href="#">Property Details</a></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- PAGE HEADER : end -->

  <!-- MAIN WRAPPER : begin -->
  <div class="main-wrapper-container">
    <div class="container">
      <div id="main-wrapper" style="background:#FFF;">
        <div class="row">
          <div class="col-md-8 col-md-push-2">

            <!-- PROPERTY DETAILS : begin -->
            <div class="property-details">

              <!-- PROPERTY IMAGES : begin -->
              <div class="property-images">
                <div class="image-list">
                  <div class="image"><img src="<%= @bucket.galleries.first.image.list.url %>" alt="商品圖一" width="720" height="450"></div>
                  <div class="image"><img src="/dummies/property_02.jpg" alt="商品圖二"></div>
                  <div class="image"><img src="/dummies/property_03.jpg" alt="商品圖三"></div>
                </div>
                <div class="images-footer">
                  <div class="images-footer-inner">
                    <div class="image-description"></div>
                    <div class="image-counter"></div>
                  </div>
                  <button class="prev-btn"><i class="fa fa-chevron-left"></i></button>
                  <button class="next-btn"><i class="fa fa-chevron-right"></i></button>
                </div>
              </div>
              <!-- PROPERTY IMAGES : end -->


              <div class="row">
                <div class="col-md-8">

                  <!-- PROPERTY PANEL : begin -->
                  <div class="property-panel">

                    <!-- OBJECT PRICE : begin -->
                    <div class="panel-item object-price">
                      <h3><%= @bucket.title %></h3>
                      <p class="price"> <strong>$<%= @bucket.price %></strong>/ 天</p>
                    </div>
                    <!-- OBJECT PRICE : end -->

                    <!-- OBJECT OWNER : begin -->
                    <div class="panel-item object-owner">
                      <h4 class="panel-item-title">擁有者</h4>
                      <div class="clearfix">
                        <div class="portrait">
                          <img src="/images/logo.png" alt="" height="150" width="150">
                          <h5 class="name">
                            <i class="ico-person"></i> <%= @bucket.organization.name %>
                          </h5>
                        </div>
                      </div>
                    </div>
                    <!-- OBJECT OWNER : end -->

                  </div>
                  <!-- PROPERTY PANEL : end -->

                </div>

                <div class="col-md-4">
                <!-- BOOK FORM : begin -->
                <div class="panel-item contact-form">

                  <h3 class="property-book-title">- 訂單 -</h4>
                  <form class="default-form" action="<%= organization_path(@bucket.organization) %>" method="get">
                    <p class="alert-message warning validation" style="display: none;"><i class="ico fa fa-exclamation-circle"></i> Please fill all fields!</p>
                
                  <!-- ARRIVAL DATE, DEPARTURE DATE : begin -->
                  <p class="form-row clearfix">
                    <span class="calendar-input input-left" title="Arrival">
                      <input type="text" name="arrival" placeholder="開始日期" data-dateformat="m/d/y">
                      <i class="fa fa-calendar"></i>
                    </span>
                  </p>
                  <p class="form-row clearfix">
                    <span class="calendar-input input-right" title="Departure">
                      <input type="text" name="departure" placeholder="結束日期" data-dateformat="m/d/y">
                      <i class="fa fa-calendar"></i>
                    </span>                  
                  </p>
                  <!-- ARRIVAL DATE, DEPARTURE DATE : end -->

                  <!-- NUMBER OF ADULTS AN CHILDREN : begin -->
                  <p class="form-row clearfix">
                    <span class="input-left" title="Quantity">
                      <input type="text" placeholder="數量">
                    </span>
                  </p>
                  <p class="form-row">
                    <button class="button submit-btn"><i class="fa fa-hand-o-up"></i> 拎北想要</button>
                  </p>
                  </form>
                </div>
                <!-- BOOK FORM : end -->

                </div>

                <div class="col-md-12">
                  
                  <!-- PROPERTY DESCRIPTION : begin -->
                  <div class="property-description">
                    <!-- DESCRIPTION TEXT : begin -->
                    <div class="description-text">
                      <h4>商品敘述</h4>
                      <p><%= @bucket.description %></p>
                    </div>
                    <!-- DESCRIPTION TEXT : end -->

                  </div>
                  <!-- PROPERTY DESCRIPTION : end -->

                </div>
              </div> <!-- row -->

            </div>
            <!-- PROPERTY DETAILS : end -->

          </div>

        </div>
      </div>
    </div>
  </div>
  <!-- MAIN WRAPPER : end -->
</div>
<!-- CORE : end -->

app/views/layouts/_header.html.erb
<!-- HEADER : begin -->
<header id="header">
  <div class="container">
    <div class="header-inner clearfix">

      <!-- HEADER BRANDING : begin -->
      <div class="header-branding">
        <a href="<%= root_path %>"><img src="/images/logo.png" alt="Bar" style="height: 50px;"></a>
      </div>
      <!-- HEADER BRANDING : end -->

      <!-- HEADER NAVBAR : begin -->
      <div class="header-navbar">

        <!-- HEADER SEARCH : begin -->
        <div class="header-search">
          <form class="default-form" action="index.html">

            <!-- SEARCH INPUT : begin -->
            <div class="search-input">
              <i class="ico fa fa-search"></i>
              <i class="close fa fa-times"></i>
              <input type="text">
            </div>
            <!-- SEARCH INPUT : end -->

            <!-- SEARCH ADVANCED : begin -->
            <div class="header-form search-advanced">
              <div class="search-advanced-inner">

                <!-- ARRIVAL DATE, DEPARTURE DATE : begin -->
                <p class="form-row clearfix">
                  <span class="calendar-input input-left" title="Arrival">
                    <input type="text" name="arrival" placeholder="開始日期" data-dateformat="m/d/y">
                    <i class="fa fa-calendar"></i>
                  </span>
                  <span class="calendar-input input-right" title="Departure">
                    <input type="text" name="departure" placeholder="結束日期" data-dateformat="m/d/y">
                    <i class="fa fa-calendar"></i>
                  </span>
                </p>
                <!-- ARRIVAL DATE, DEPARTURE DATE : end -->

                <!-- NUMBER OF OBJ : begin -->
                <p class="form-row clearfix">
                  <input type="text" name="number" placeholder="數量">
                </p>
                <!-- NUMBER OF OBJ : end -->


                <hr class="form-divider">
                <p class="form-row">
                  <button class="submit-btn button"><i class="fa fa-search"></i> Search</button>
                </p>

              </div>
            </div>
            <!-- SEARCH ADVANCED : end -->

          </form>
        </div>
        <!-- HEADER SEARCH : end -->

        <!-- HEADER MENU : begin -->
        <div class="header-menu">
          <a href="<%= buckets_path %>"><button class="header-btn"> 探索商品 </button></a>
        </div>
        <div class="header-menu">
          <a href="<%= organizations_path %>"><button class="header-btn"> 探索社團 </button></a>
        </div>

    <!--
        <div class="header-menu">
          <button class="header-btn">Menu <i class="fa fa-angle-down"></i></button>
          <nav class="header-nav">
            <ul>
              <li class="has-submenu">
                <a href="index.html">Home</a>
                <ul class="sub-menu">
                  <li><a href="home-2.html">Home 2</a></li>
                  <li><a href="home-3.html">Home 3</a></li>
                  <li class="has-submenu">
                    <a href="index.html">Dummy Item</a>
                    <ul class="sub-menu">
                      <li><a href="index.html">Dummy 1</a></li>
                      <li><a href="index.html">Dummy 2</a></li>
                    </ul>
                  </li>
                </ul>
              </li>
              <li class="has-submenu">
                <a href="properties-listing-grid.html">Property Listing</a>
                <ul class="sub-menu">
                  <li><a href="properties-listing-grid.html">Grid Layout</a></li>
                  <li><a href="properties-listing-list.html">List Layout</a></li>
                </ul>
              </li>
              <li class="has-submenu">
                <a href="property-details-swap.html">Property Detail</a>
                <ul class="sub-menu">
                  <li><a href="property-details-swap.html">Detail (Swap)</a></li>
                  <li><a href="property-details-book.html">Detail (Book)</a></li>
                  <li><a href="property-details-rent.html">Detail (Rent)</a></li>
                </ul>
              </li>
              <li><a href="shortcodes.html">Shortcodes</a></li>
              <li><a href="about-us.html">About Us</a></li>
              <li><a href="contact-us.html">Contact Us</a></li>
              <li><a href="privacy-policy.html">Privacy Policy</a></li>
              <li><a href="terms-conditions.html">Terms &amp; Conditions</a></li>
            </ul>
          </nav>
        </div>
    -->        

        <!-- HEADER MENU : end -->

        <!-- HEADER TOOLS : begin -->
        <div class="header-tools">
          <!-- HEADER LANGUAGE : begin -->
          <!-- <div class="header-language">
            <button class="header-btn">EN <i class="fa fa-angle-down"></i></button>
            <nav class="header-nav">
              <ul class="custom-list">
                <li class="active"><a href="#">EN</a></li>
                <li><a href="#">DE</a></li>
                <li><a href="#">FR</a></li>
                <li><a href="#">IT</a></li>
              </ul>
            </nav>
          </div> -->
          <!-- HEADER LANGUAGE : end -->

          <% if user_signed_in? %>
          <div class="header-login">
            <button class="register-toggle header-btn" >            
              <i class="fa fa-user"></i> 
              <%= current_user.email.split("@")[0] + "(" + current_user.organization + ")"%>
              <i class="fa fa-angle-down"></i>
            </button>
            <div class="header-form" style="width:250px;">
                <ul class="custom-list">
                  <li><%= link_to "我的商品", admin_path %></li>
                  <li><%= link_to "修改個人資料", edit_user_registration_path %></li>
                </ul>
            </div>

          </div>
          <div class="header-register">
            <a class="header-btn"
               href="<%= destroy_user_session_path %>"
               data-method="delete">
              <i class="fa fa-sign-out"></i> 登出 
            </a>
          </div>
          <!-- HEADER REGISTER : end -->
          <% else %>
          <!-- HEADER REGISTER : begin -->
          <div class="header-register">
            <button class="register-toggle header-btn"><i class="fa fa-plus-circle"></i> 註冊 </button>
            <div class="header-form">
              <%= form_for @user, url: registration_path(@user),
                  html: { class: "default-form"} do |f| %>
                <p class="alert-message warning"><i class="ico fa fa-exclamation-circle"></i> 所有的欄位都要填喔！<i class="fa fa-times close"></i></p>
                <p class="form-row">
                  <%= f.text_field :email, placeholder: "email",
                      class: "required email"  %>
                </p>
                <p class="form-row">
                  <%= f.password_field :password, 
                    placeholder: "密碼", class: "required" %>
                </p>
                <p class="form-row">
                  <%= f.password_field :password_confirmation, 
                    placeholder: "重複輸入您的密碼", class: "required" %>
                </p>
                <p class="form-row">
                  <%= f.submit "註冊", class: "submit-btn button" %>
                </p>
              <% end %>
            </div>
          </div>
          <!-- HEADER REGISTER : end -->

          <!-- HEADER LOGIN : begin -->
          <div class="header-login">
            <button class="login-toggle header-btn"><i class="fa fa-power-off"></i> Login</button>
            <div class="header-form">
              <%= form_for @user, url: user_session_path,
                  html: { class: "default-form"} do |f| %>
                <p class="alert-message warning"><i class="ico fa fa-exclamation-circle"></i> 所有的欄位都要填喔！ <i class="fa fa-times close"></i></p>
                <p class="form-row">
                  <%= f.text_field :email, placeholder: "email",
                      class: "required email" %>
                </p>
                <p class="form-row">
                  <%= f.password_field :password, 
                    placeholder: "密碼", class: "required" %>
                </p>
                <p class="form-row">
                  <button class="submit-btn button"><i class="fa fa-power-off"></i> Login</button>
                </p>
                <p class="form-row forgot-password">
                  <a href="#"> 忘記密碼 </a>
                </p>
              <% end %>
            </div>
          </div>
          <!-- HEADER LOGIN : end -->
          <% end %>

          <% if user_signed_in? %>
            <!-- HEADER ADD OFFER : begin -->
            <span class="header-add-offer">
            <%= link_to "新增商品", new_admin_bucket_path ,{ :class=>"fa fa-plus button" }%> 
            <!-- HEADER ADD OFFER : end -->
          <% else %>
            <span class="header-add-offer">
            <div class="fa button"> 免費封測中！ </div> 
          <% end %>
          

        </div>
        <!-- HEADER TOOLS : end -->

      </div>
      <!-- HEADER NAVBAR : end -->

      <!-- SEARCH TOGGLE : begin -->
      <button class="search-toggle button"><i class="fa fa-search"></i></button>
      <!-- SEARCH TOGGLE : end -->

      <!-- NAVBAR TOGGLE : begin -->
      <button class="navbar-toggle button"><i class="fa fa-bars"></i></button>
      <!-- NAVBAR TOGGLE : end -->

    </div>
  </div>
</header>
<!-- HEADER : end -->

app/views/organizations/_organization_listing.html.erb
<!-- PROPERTIES LISTING : begin -->
<div class="properties-listing">

  <!-- PROPERTIES LISTING HEADER : begin -->
  <div class="properties-listing-header clearfix">

    <!-- LIST SORTING : begin -->
    <div class="list-sorting">
      <form class="default-form" action="index.html">
        <h5>排序依照</h5>
        <span class="select-box">
          <select name="sort-alphabetical">
            <option value="asc">A to Z</option>
            <option value="desc">Z to A</option>
          </select>
        </span>
        <span class="select-box">
          <select name="sort-rating">
            <option value="asc">評價 &uarr;</option>
            <option value="desc">評價 &darr;</option>
          </select>
        </span>
        <span class="select-box">
          <select name="sort-price">
            <option value="asc">價格 &uarr;</option>
            <option value="desc">價格 &darr;</option>
          </select>
        </span>
      </form>
    </div>
    <!-- LIST SORTING : end -->

    <!-- LIST LAYOUT : begin -->
    <div class="list-layout">
      <button class="button" data-layout="grid"><i class="fa fa-th"></i></button>
      <button class="button active" data-layout="list"><i class="fa fa-list-ul"></i></button>
    </div>
    <!-- LIST LAYOUT : end -->
  </div>
  <!-- PROPERTIES LISTING HEADER : end -->

  <!-- PROPERTY LIST : begin -->
  <ul class="custom-list clearfix property-list layout-list">
    <% Organization.all.each do |organization| %>
    <li class="property first-in-row odd">
      <a href="<%= organization_path(organization) %>" class="property-thumb">
        <img src="<%= organization.galleries.first.image.list.url %>" alt="">
        <span class="overlay"><span><i class="fa fa-search"></i> View More</span></span>
      </a>
      <div class="property-content">
        <h4 class="property-title"><a href="#"><%= organization.name %></a></h4>
        <h5 class="property-location"><%= organization.location %></h5>
        <p class="property-description"><%= organization.description %></p>
        <div class="property-price-rating">
          <div class="property-rating">
            <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
          </div>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
  <!-- PROPERTY LIST : end -->

  <!-- PROPERTIES LISTING FOOTER : begin -->
  <div class="properties-listing-footer clearfix">
    <div class="default-form">
      <span class="select-box links">
        <select name="listing-pagination">
          <option value="properties-listing-grid.html?page=1">Page 1</option>
          <option value="properties-listing-grid.html?page=2">Page 2</option>
          <option value="properties-listing-grid.html?page=3">Page 3</option>
          <option value="properties-listing-grid.html?page=4">Page 4</option>
          <option value="properties-listing-grid.html?page=5">Page 5</option>
          <option value="properties-listing-grid.html?page=6">Page 6</option>
          <option value="properties-listing-grid.html?page=7">Page 7</option>
          <option value="properties-listing-grid.html?page=8">Page 8</option>
          <option value="properties-listing-grid.html?page=9">Page 9</option>
          <option value="properties-listing-grid.html?page=10">Page 10</option>
        </select>
      </span>
    </div>
  </div>
  <!-- PROPERTIES LISTING FOOTER : end -->

</div>
<!-- PROPERTIES LISTING : end -->